### ISSUE TITLE
Getting neighbors should use node objects; not node ids

### ISSUE THREAD

**Issue by m-bilgic** [m-bilgic/CS583#10]
https://github.com/m-bilgic/CS583/blob/master/project/solutions/classifiers.py#L34
https://github.com/m-bilgic/CS583/blob/master/project/solutions/classifiers.py#L37
https://github.com/m-bilgic/CS583/blob/master/project/solutions/classifiers.py#L43

**Comment by jshao3** [comment]
Fixed
