### ISSUE TITLE
Aggregate type in phase 2

### ISSUE THREAD

**Issue by m-bilgic** [m-bilgic/CS583#3]
https://github.com/m-bilgic/CS583/blob/master/project/assigned/run_phase2.py#L54

Aggregate is now hard-coded as count aggregate. We need to choose it based on the aggregate argument.

**Comment by jshao3** [comment]
add the pick_aggregrator() in classifiers.py

**Comment by jshao3** [comment]
add the pick_aggregrator() in classifiers.py
