### ISSUE TITLE
Edge should accept Node objects in its constructor

### ISSUE THREAD

**Issue by m-bilgic** [m-bilgic/CS583#8]
https://github.com/m-bilgic/CS583/blob/master/project/solutions/data_utils.py#L23

Edge constructor should accept node objects, not node ids. Have a dictionary that maps node ids to node objects, and at https://github.com/m-bilgic/CS583/blob/master/project/solutions/data_utils.py#L16 you can create a Node object, and put it into the dictionary. When creating an Edge object, you can get the node objects from this dictionary. If a node object does not exist, you can ignore.

**Comment by jshao3** [comment]
Fixed
